services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
      NODE_OPTIONS: --enable-source-maps
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: octocat
      MYSQL_DATABASE: value
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./:/src

  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: octocat
  #     MYSQL_DATABASE: value
  #     TZ: UTC
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - db:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: octocat
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:
