services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: octocat
      MYSQL_DATABASE: value
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/src

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: octocat
      MYSQL_DATABASE: value
      # TZ: UTC
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-h127.0.0.1", "ping"]
      interval: 1s

volumes:
  db:

networks:
  default:
    driver: bridge
