services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    depends_on:
      - db
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: octocat
      DB_NAME: value
    links:
      - db
    volumes:
      - ./:/src

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: octocat
      MYSQL_DATABASE: value
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:

networks:
  default:
    driver: bridge