services:
  dev:
    extends:
      file: ../compose.yml
      service: backend
    volumes:
      # Mount the parent directory (project root) to /workspace
      - ../..:/workspaces:cached    
    # Remove network_mode and use networks instead
    networks:
      - default
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      NODE_ENV: development
      MYSQL_HOST: db

  db:
    extends:
      file: ../compose.yml
      service: db
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: default
    driver: bridge

volumes:
  db: