services:
  dev:
    extends:
      file: ../compose.yml
      service: backend
    build: .
    ports:
      - "4200:4200"
    volumes:
      # Mount the parent directory (project root) to /workspace
      - ..:/src:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      NODE_ENV: development

  db:
    extends:
      file: ../compose.yml
      service: db

volumes:
  db: