name: Frontend

on:
  push:
    paths:
      - 'frontend/**/*'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**/*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i eslint
          npm i @microsoft/eslint-formatter-sarif
        working-directory: ./frontend
      - run: npm run lint
        working-directory: ./frontend